[package]
name = "rust-single"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.35"
futures = "0.3.30"
rdkafka = "0.36.2"
tokio = { version = "1.18", features = ["full"] }
